### PR TITLE
scraped shopify jobs

### PR DESCRIPTION
**Pull request by munnavuyyuru**
added shopify scraped jobs

### CODE REVIEW

**Comment by dotslashbit** [comment]
@munnavuyyuru I have updated the codebase and now we are also scrapping every job's description, please refer to the code or ask me for any help.

**Comment by munnavuyyuru** [comment]
@dotslashbit ,Working on it ,but codebase is same when fetched using upstream

**Comment by dotslashbit** [comment]
@munnavuyyuru have you done git pull origin main?

**Comment by munnavuyyuru** [comment]
@dotslashbit yeah

**Comment by munnavuyyuru** [comment]
closing this PR, make another pr

**Comment by dotslashbit** [comment]
@munnavuyyuru I would say always create a new branch per issue

**Pull request closed without merging**
