### PR TITLE
Added dropbox scrapper

### PR DESCRIPTION
**Pull request by ilumin**
#26 Dropbox scrapper added (closes)

### CODE REVIEW

**Comment by dotslashbit** [comment]
@ilumin Thank you so much for your contribution. I can't access my laptop right now, can you please send a screen recording of the output so that I can confirm it's working and I'll merge it

**Comment by dotslashbit** [comment]
@ilumin and update the description to closes #<issue number> keep it in the first line.

It'll automatically close the issue when the pr gets merged

**Comment by ilumin** [comment]
@dotslashbit here you are

<div>
    <a href="https://www.loom.com/share/d5ac66a495b84140a9e4b8c5a6d6ef5f">
      <p>Career Craft Scrapper - Dropbox - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/d5ac66a495b84140a9e4b8c5a6d6ef5f">
      
    </a>
  </div>

**Review by dotslashbit — APPROVED** [review]

**Comment by dotslashbit** [comment]
@ilumin merged 🎉. 

Thank you so much for your contribution. I hope you'll contribute even more to this project and make it the best platform for job seekers.

Let's go 🔥

**Pull request merged**
