### PR TITLE
Scrap CircleCI Jobs

### LINKED ISSUE #21: Scrap CircleCI Jobs
Link --> https://circleci.com/careers/

Please comment down below if you want to work on this

Please ping me if you need any help or clarification

### PR DESCRIPTION
**Pull request by Goutamchoudhary907**
close #21 

Successfully compiled
Screenshot 2024-10-05 205914

Circle Jobs details
Screenshot 2024-10-08 091343

I add job experience section and extract  experience part from skills and add it in seperate  experience  section and also add job remote availability section

### CODE REVIEW

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 This looks great but we are now scrapping even more fields like location, salary, experience, etc. I would say take a look at other scrappers, you'll know what other fields you need to add

**Comment by Goutamchoudhary907** [comment]
Ok i will check

**Comment by Goutamchoudhary907** [comment]
@dotslashbit Bro now check

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 This is great work and I get your point about not keeping experience and remote fields, but we need those so that we can seamlessly add those to the DB. Its almost done

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 awesome, merging it right now

**Review by dotslashbit — APPROVED** [review]

**Comment by dotslashbit** [comment]
@Goutamchoudhary907 this is such a great work. Thank you so much for being patient and incrementally working on this issue 🙏

**Comment by Goutamchoudhary907** [comment]
@dotslashbit  Thanks a lot for merging and guide me throughout the issue , i will look forward to contributing to other issues

**Pull request merged**
