### PR TITLE
Added Trello Scrapper

### PR DESCRIPTION
**Pull request by bhima2001**
Used https://www.atlassian.com/company/careers/all-jobs?search=Trello this url to get all the jobdetails

### CODE REVIEW

**Comment by dotslashbit** [comment]
@bhima2001 can you send a screen recording of the output, thanks

**Comment by bhima2001** [comment]
TrelloSS
This photo contains all the jobs from trello

**Comment by dotslashbit** [comment]
It's great but can you modify it to get all atlassian jobs instead of trello jobs.

I didn't know that trello comes under atlassian. Sorry for this

**Comment by bhima2001** [comment]
I have changed the url and now fetching all jobs from entire atlassian instead of only trello

**Comment by dotslashbit** [comment]
@bhima2001 whenever you are finished, just send a screen recording or screenshot of the output so that it'll be easy and fast to verify, thanks

**Comment by bhima2001** [comment]
Screenshot 2024-09-24 101505
This is a picture of some of the jobs from atlassian. I scraped 298 job postings from atlassian's career page

**Comment by dotslashbit** [comment]
Awesome it's working great, I'll review and merge it

**Review by dotslashbit — APPROVED** [review]

**Comment by dotslashbit** [comment]
@bhima2001 Thank you so much for your contribution. It's a high impact contribution and I can't thank you enough for this. I hope you'll stick with this project and contribute in the future.

**Pull request merged**
